'use client';
import { useEffect, useState } from "react";
import { VideoPlayer } from "@/components/Video/VideoPlayer";
import { SocketProvider } from "@/context/SocketContext";

// import type { Metadata } from "next";
import { io } from "socket.io-client";

// export const metadata: Metadata = {
//   title: "Video Chat App",
//   description: "Generated by create next app",
// };


export default function Home() {

  return (
    <SocketProvider>
      <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm lg:flex">
        <div className="fixed bottom-0 left-0 flex h-48 w-full items-end justify-center bg-gradient-to-t from-white via-white dark:from-black dark:via-black lg:static lg:h-auto lg:w-auto lg:bg-none">
          <h1>Video Chat App</h1>
          <VideoPlayer />
          {/* Notification */}
        </div>
      </div>
    </SocketProvider>
  );
}
